version: '3.8'

services:
  grafana:
    image: grafana/grafana:8.1.1
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_data:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: https://grafana.sksat.net
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: grafana-renderer:debug

  grafana-renderer:
    image: grafana/grafana-image-renderer:3.0.1
    restart: always
    ports:
      - 8081:8081
    environment:
      ENABLE_METRICS: 'true'

  prometheus:
    image: prom/prometheus:v2.29.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always

  prometheus-blackbox:
    image: prom/blackbox-exporter:v0.19.0
    container_name: blockbox
    ports:
      - 9115:9115
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.22.2
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/config.yaml"
    ports:
      - 9093:9093
    restart: always
