version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
  prometheus-blackbox:
    image: prom/blackbox-exporter
    container_name: blockbox
    ports:
      - 9115:9115
    restart: always
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/config.yaml"
    ports:
      - 9093:9093
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_data:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: https://grafana.sksat.net
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: grafana-renderer:debug
  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ENABLE_METRICS: 'true'
