global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  - /etc/prometheus/alert.rules

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    file_sd_configs:
    - files:
      - 'targets.json'
  - job_name: 'ap-prom'
    static_configs:
      - targets: ["192.168.10.123:9100"]
  - job_name: 'blackbox-icmp'
    scrape_interval:     5s
    metrics_path: '/probe'
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 1.1.1.1
        - 8.8.8.8
        - 192.168.1.1
        - 192.168.10.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blockbox:9115 

  - job_name: 'blackbox'
    params:
      module: [http_2xx]
    file_sd_configs:
    - files:
      - 'blackbox-targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blockbox:9115 
