name: validate docker-compose.yml

on:
  push:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/compose-validate.yml'

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: validate
        run: |
          docker-compose -f docker-compose.yml config
